### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Shubham-Rasal** [Shubham-Rasal/flow-forge#4]
- [x] setup magic link auth
- [x] setup github oauth 
- [x] way to collect waitlist emails
- [x] Figure out new node creation
- [ ] create db schema
- [x] implement state management
- [ ] give waitlist people restricted access
- [ ] implement feedback ui
- [ ] create a update profile page

**Comment by Shubham-Rasal** [comment]
- [x] add about page
- [ ] local first app using indexDB
- [ ] add vercel analytics
- [ ] make a leaking node for showing update in progress
